### ISSUE TITLE
Coderwall badge does not render

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/surf-2012#2]
I tossed the code in the mako template, but the badge does not render. I played around with the CSS a bit, no luck.

**Comment by dtgay** [comment]
Using `<div>` rather than `<section>` doesn't help.

Neither does removing the if statement that's importing the script and style.

Neither does changing the positioning.

**Comment by dtgay** [comment]
@decause tested the badge stand-alone, it didn't even work. Looks like the problem may be on Coderwall's end. He's still investigating.

**Comment by dtgay** [comment]
Needed to include jQuery itself >.<

**Comment by decause** [comment]
Pull Request:
https://gist.github.com/3146106
